[package]
name = "aoc18"
version = "0.1.0"
authors = ["Max Stanley <github@maxstanley.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.11"
